import { FilterStyle, FrameStyle } from './types';

export const FILTER_STYLES: FilterStyle[] = [
  {
    id: 'none',
    name: '필터 없음',
    preview: '□',
    type: 'none',
  },
  {
    id: 'grayscale',
    name: '흑백',
    preview: '●',
    type: 'grayscale',
  },
  {
    id: 'sepia',
    name: '세피아',
    preview: '◐',
    type: 'sepia',
  },
  {
    id: 'vintage',
    name: '빈티지',
    preview: '◑',
    type: 'vintage',
  },
  {
    id: 'warm',
    name: '따뜻한 색감',
    preview: '◕',
    type: 'warm',
  },
  {
    id: 'cool',
    name: '차가운 색감',
    preview: '◔',
    type: 'cool',
  },
  {
    id: 'dramatic',
    name: '드라마틱',
    preview: '◈',
    type: 'dramatic',
  },
];

export const FRAME_STYLES: FrameStyle[] = [
  {
    id: 'none',
    name: '액자 없음',
    preview: '□',
    borderWidth: 0,
    borderColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    shadowColor: 'transparent',
  },
  {
    id: 'classic',
    name: '클래식',
    preview: '■',
    borderWidth: 20,
    borderColor: '#8B4513',
    shadowBlur: 15,
    shadowOffset: 5,
    shadowColor: 'rgba(0,0,0,0.3)',
    innerBorder: {
      width: 3,
      color: '#DAA520',
    },
    pattern: 'vintage',
  },
  {
    id: 'modern',
    name: '모던',
    preview: '▪',
    borderWidth: 12,
    borderColor: '#2C2C2C',
    shadowBlur: 20,
    shadowOffset: 3,
    shadowColor: 'rgba(0,0,0,0.4)',
    pattern: 'modern',
  },
  {
    id: 'gold',
    name: '골드',
    preview: '◆',
    borderWidth: 25,
    borderColor: '#FFD700',
    shadowBlur: 25,
    shadowOffset: 8,
    shadowColor: 'rgba(0,0,0,0.2)',
    innerBorder: {
      width: 2,
      color: '#FFA500',
    },
    pattern: 'gold',
  },
  {
    id: 'wood',
    name: '우드',
    preview: '▦',
    borderWidth: 30,
    borderColor: '#8B4513',
    shadowBlur: 12,
    shadowOffset: 4,
    shadowColor: 'rgba(139,69,19,0.3)',
    innerBorder: {
      width: 4,
      color: '#A0522D',
    },
    pattern: 'wood',
  },
  {
    id: 'vintage',
    name: '빈티지',
    preview: '▣',
    borderWidth: 35,
    borderColor: '#F5DEB3',
    shadowBlur: 18,
    shadowOffset: 6,
    shadowColor: 'rgba(101,67,33,0.4)',
    innerBorder: {
      width: 5,
      color: '#DEB887',
    },
    pattern: 'vintage',
  },
];
